"""the one place a codice fiscale is validated.

a real codice fiscale is 16 characters: 6 letters, 2-digit year, month
letter, 2-digit day (+40 for women), 4-character birthplace code, and a check
character computed from the first 15 (DM 23/12/1976). when two people would
collide, digits are swapped for the letters LMNPQRSTUV ("omocodia"), and the
check character is computed over the swapped string.

a valid format proves only that - it does not prove who a person is.

every fixture, the training set and the dental-notes model use a synthetic
shape, 4 letters and 12 digits, which no real code has. it is accepted only
while CLINIC_ALLOW_SYNTHETIC_CF is on (the default for development). a
real-data release must turn it off (P17) - with it on, a mistyped real code
is not a risk, but a synthetic one is a record nobody can be.
"""

import os
import re

SYNTHETIC = re.compile(r"^[A-Z]{4}[0-9]{12}$")
_D = "[0-9LMNPQRSTUV]"
REAL = re.compile(rf"^[A-Z]{{6}}{_D}{{2}}[ABCDEHLMPRST]{_D}{{2}}[A-Z]{_D}{{3}}[A-Z]$")
OMOCODIA = {c: str(i) for i, c in enumerate("LMNPQRSTUV")}

# value of each character in an odd (1st, 3rd, ...) and even position
_ODD = dict(zip("0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ",
                [1, 0, 5, 7, 9, 13, 15, 17, 19, 21,
                 1, 0, 5, 7, 9, 13, 15, 17, 19, 21, 2, 4, 18, 20, 11, 3, 6, 8, 12, 14, 16, 10, 22, 25, 24, 23]))
_EVEN = {**{str(i): i for i in range(10)}, **{c: i for i, c in enumerate("ABCDEFGHIJKLMNOPQRSTUVWXYZ")}}


def is_production(env=None):
    env = os.environ if env is None else env
    return env.get("CLINIC_ENV", "").strip().lower() == "production"


def synthetic_allowed(env=None):
    # production never allows synthetic codes, whatever the flag says
    env = os.environ if env is None else env
    if is_production(env):
        return False
    return env.get("CLINIC_ALLOW_SYNTHETIC_CF", "1").strip().lower() not in ("0", "false", "no", "off")


def guard_refusal(env, real_cf_count):
    """why the apps must not start, or None. pure, so every branch is testable.

    two signals, because an env var alone is forgotten: production says so
    explicitly, OR the database already holds real-format codes - real data
    is present whether or not anyone set CLINIC_ENV."""
    flag_on = env.get("CLINIC_ALLOW_SYNTHETIC_CF", "1").strip().lower() not in ("0", "false", "no", "off")
    if is_production(env) and flag_on and "CLINIC_ALLOW_SYNTHETIC_CF" in env:
        return "CLINIC_ALLOW_SYNTHETIC_CF is on while CLINIC_ENV=production"
    if real_cf_count and synthetic_allowed(env):
        return (f"the database holds {real_cf_count} real codice fiscale(s) while synthetic codes "
                "are still accepted - set CLINIC_ALLOW_SYNTHETIC_CF=0 (or CLINIC_ENV=production)")
    return None


def guard_or_exit(db_path):
    # startup guard for run.py and patient_run.py, sibling of disk_guard
    import sqlite3
    import sys
    from pathlib import Path
    real = 0
    if Path(db_path).exists():
        conn = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
        try:
            real = sum(1 for (cf,) in conn.execute("SELECT codice_fiscale FROM patients") if is_real(cf))
        except sqlite3.OperationalError:
            real = 0  # no patients table yet: a fresh install holds no real data
        finally:
            conn.close()
    reason = guard_refusal(os.environ, real)
    if reason:
        print(f"refusing to start: {reason}", file=sys.stderr)
        sys.exit(1)


def normalize(value):
    # for input boundaries only: people type codes in lower case and with
    # spaces. storage and urls always carry the normalised form.
    return re.sub(r"\s+", "", value or "").upper()


def check_char(first15):
    total = sum(_ODD[c] if i % 2 == 0 else _EVEN[c] for i, c in enumerate(first15))
    return chr(ord("A") + total % 26)


def is_real(value):
    if not REAL.match(value or ""):
        return False
    day = int("".join(OMOCODIA.get(c, c) for c in value[9:11]))
    if not (1 <= day <= 31 or 41 <= day <= 71):
        return False
    return check_char(value[:15]) == value[15]


def is_valid(value):
    """True for a real code with a correct check character, or - only while
    synthetic codes are allowed - the synthetic development shape. expects the
    normalised form; call normalize() on raw input first."""
    if is_real(value):
        return True
    return synthetic_allowed() and bool(SYNTHETIC.match(value or ""))


def selftest():
    # published example codes, not generated by this module
    for good in ("RSSMRA85T10A562S", "RSSMRA85T10A56NS"[:15] + check_char("RSSMRA85T10A56N")):
        assert is_real(good), f"1: {good} is a valid code"
    assert check_char("RSSMRA85T10A562") == "S", "1: the documented example's check character is S"
    # the regression P02 exists for: the old regex rejected every real code
    assert not SYNTHETIC.match("RSSMRA85T10A562S") and is_valid("RSSMRA85T10A562S"), "2: a real code must pass"
    bad = {
        "RSSMRA85T10A562T": "wrong check character",
        "RSSMRA85Z10A562S": "Z is not a month letter",
        "RSSMRA85T32A562S": "day 32 does not exist",
        "RSSMRA85T10A562": "too short",
        "RSSMRA85T10A562S1": "too long",
        "' OR 1=1 --     ": "not a code at all",
        "": "empty",
        None: "missing",
    }
    for value, why in bad.items():
        assert not is_valid(value), f"3: {value!r} must be refused ({why})"
    assert normalize(" rssmra 85t10 a562s ") == "RSSMRA85T10A562S", "4: normalize strips spaces and upper-cases"
    assert not is_valid(" rssmra85t10a562s"), "4: is_valid expects the normalised form"
    old = os.environ.get("CLINIC_ALLOW_SYNTHETIC_CF")
    try:
        os.environ.pop("CLINIC_ALLOW_SYNTHETIC_CF", None)
        assert is_valid("RSSI800010150100"), "5: synthetic codes pass by default in development"
        os.environ["CLINIC_ALLOW_SYNTHETIC_CF"] = "0"
        assert not is_valid("RSSI800010150100"), "5: with the flag off, a synthetic code is refused"
        assert is_valid("RSSMRA85T10A562S"), "5: and a real one still passes"
    finally:
        if old is None:
            os.environ.pop("CLINIC_ALLOW_SYNTHETIC_CF", None)
        else:
            os.environ["CLINIC_ALLOW_SYNTHETIC_CF"] = old
    # 6. the production guard (enforced at startup by run.py / patient_run.py)
    assert not synthetic_allowed({"CLINIC_ENV": "production", "CLINIC_ALLOW_SYNTHETIC_CF": "1"}), \
        "6: production never allows synthetic codes"
    assert guard_refusal({}, 0) is None, "6: dev with synthetic data starts"
    assert guard_refusal({}, 3), "6: real codes present while synthetic is on must refuse"
    assert guard_refusal({"CLINIC_ALLOW_SYNTHETIC_CF": "0"}, 3) is None, "6: real data with the flag off starts"
    assert guard_refusal({"CLINIC_ENV": "production", "CLINIC_ALLOW_SYNTHETIC_CF": "1"}, 0), \
        "6: production with the flag explicitly on must refuse, even before real data"
    assert guard_refusal({"CLINIC_ENV": "production"}, 5) is None, "6: production, flag unset, real data: starts"
    print("selftest ok")


if __name__ == "__main__":
    import sys
    if "--selftest" in sys.argv:
        selftest()
