"""writes docs/release/REFERENCE.md from the code itself: every route of the three
apps (method, path, endpoint) and every table of a fresh database with its
columns. hand-written api and schema docs drift; this one cannot, because the
selftest fails when the file on disk differs from what the code says now.

    .venv/bin/python release_docs.py            # rewrite the file
    .venv/bin/python release_docs.py --selftest # fail if it is stale
"""

import os
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "docs" / "release" / "REFERENCE.md"


def routes():
    # the patient app refuses to start without its signing key; a throwaway one
    # is enough to read the url map, which is all this does
    from app import create_app
    from patient_app import create_patient_app
    from site_app import create_site_app
    with tempfile.TemporaryDirectory() as tmp:
        env = Path(tmp) / ".env.patient"
        env.write_text("SECRET_KEY=" + "0" * 64 + "\n")
        apps = (("staff (:5000)", create_app()), ("patient (:5001)", create_patient_app(env)),
                ("public site (:5002)", create_site_app()))
        out = []
        for name, app in apps:
            rows = sorted((r.rule, ",".join(sorted(r.methods - {"HEAD", "OPTIONS"})), r.endpoint)
                          for r in app.url_map.iter_rules() if r.endpoint != "static")
            out.append((name, rows))
    return out


def tables():
    import storage
    with tempfile.TemporaryDirectory() as tmp:
        conn = storage.init_db(str(Path(tmp) / "ref.sqlite"))
        try:
            names = [r[0] for r in conn.execute("SELECT name FROM sqlite_master WHERE type = 'table'"
                                                " AND name NOT LIKE 'sqlite_%' ORDER BY name")]
            return [(n, [r[1] for r in conn.execute(f'PRAGMA table_info("{n}")')]) for n in names]
        finally:
            conn.close()


def render():
    lines = ["# Reference: routes and schema", "",
             "Generated by `release_docs.py` from the code; do not edit by hand. The selftest fails when",
             "this file is stale.", ""]
    for name, rows in routes():
        lines += [f"## Routes - {name}", "", "| Method | Path | Endpoint |", "|---|---|---|"]
        lines += [f"| {m} | `{r}` | `{e}` |" for r, m, e in rows]
        lines.append("")
    lines += ["## Database tables (fresh `storage.init_db`)", "", "| Table | Columns |", "|---|---|"]
    lines += [f"| `{n}` | {', '.join(cols)} |" for n, cols in tables()]
    return "\n".join(lines) + "\n"


def main(argv):
    os.environ.setdefault("DISK_GUARD_DISARMED", "1")
    text = render()
    if "--selftest" in argv:
        current = OUT.read_text() if OUT.exists() else ""
        assert current == text, "docs/release/REFERENCE.md is stale: run python release_docs.py"
        assert "| `patients` |" in text and "`/login`" in text, "the reference lost its tables or routes"
        print("selftest ok")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
